# Site wide configuration

title: PolettiX!
locale: en_US
#url: "http://polettix.it/" # the base hostname & protocol for your site
#url: '/blog'
#baseurl: '/blog'
encoding: 'utf-8'
twitter_username: polettix
github_username:  polettix
timezone: 'Europe/Rome'


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true


# Site owner
owner:
  name: Flavio Poletti
  avatar: flavio-self-color.png
  bio: "Irreducible Perler."
  email: flavio@polettix.it
  disqus-shortname: polettix
  twitter: polettix
  google:
    plus:
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: polettix
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: flaviopoletti
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: flaviopoletti
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  metacpan: polettix

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "bin", '.leaveme', 'images/_host']
